version: '3.8'
services:
  coordinator:
    image: alpine:latest
    container_name: hub_coordinator
    command: sh -c "echo 'Iniciando HUB...' && sleep 3600"
  worker-1:
    image: alpine:latest
    container_name: peer_worker_1
    command: sh -c "echo 'Iniciando WORKER...' && sleep 3600"
